//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunar.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lunar.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import sys
        ///import clr
        ///clr.AddReference(&apos;Lunar.Core&apos;)
        ///clr.AddReference(&apos;Lunar.Server&apos;)
        ///clr.AddReference(&apos;System&apos;)
        ///import npc_common 
        ///from Lunar.Server.Utilities import *
        ///from Lunar.Server.World.BehaviorDefinition import *
        ///from Lunar.Server.World.Actors import *
        ///import random
        ///
        ///class CombatNPCState(IActorState[NPC]):
        ///	def __init__(self):
        ///		return
        ///		
        ///	def OnEnter(self, npc):
        ///		nextAttackTimer = GameTimer(1000)
        ///		npc.GameTimers.Register(&quot;nextAttackTimer&quot;, nextAttackTimer)
        ///		
        ///	def OnExit(self,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AggressiveNPCBehavior {
            get {
                return ResourceManager.GetString("AggressiveNPCBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import sys
        ///import clr
        ///import npc_common
        ///from Lunar.Server.Utilities import *
        ///from Lunar.Server.World.BehaviorDefinition import *
        ///
        ///
        ///class AggressiveNPCBehaviorDefinition(ActorBehaviorDefinition):
        ///	def __init__(self):
        ///		print(&apos;not implemented&apos;)
        ///	
        ///	def Update(self, npc, gameTime):
        ///		print(&apos;not implemented&apos;)
        ///
        ///	def OnCreated(self, npc):
        ///		print(&apos;not implemented&apos;)
        ///		
        ///
        ///	def Attack(self, npc, target):
        ///		print(&apos;not implemented&apos;)
        ///        return 0
        ///		
        ///	def Attacked(self, npc, attacker, damage_delt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultNPCBehavior {
            get {
                return ResourceManager.GetString("DefaultNPCBehavior", resourceCulture);
            }
        }
    }
}
