<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Lunar.Graphics</RootNamespace>
    <AssemblyName>Lunar.Graphics</AssemblyName>
    <Authors>John Lamontagne</Authors>
    <Product>Lunar.Graphics</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lunar.Core\Lunar.Core.csproj" />
  </ItemGroup>

</Project>
