<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Lunar.Client</RootNamespace>
    <AssemblyName>Lunar.Client</AssemblyName>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <Authors>John Lamontagne</Authors>
    <Product>Lunar.Client</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
    <PackageReference Include="AscensionGameDev.Lidgren.Network" Version="1.8.0.13" />
    <PackageReference Include="MonoGame.Penumbra.DesktopGL" Version="3.0.0" />
    <PackageReference Include="MonoGame.QuakeConsole.DesktopGL" Version="3.0.0" />
    <PackageReference Include="MonoGame.QuakeConsole.ManualInterpreter.DesktopGL" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lunar.Core\Lunar.Core.csproj" />
    <ProjectReference Include="..\Lunar.Graphics\Lunar.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icon.bmp" />
    <None Update="Client Data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>

</Project>
