<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Lunar.Tools.Editor.Contracts</RootNamespace>
    <AssemblyName>Lunar.Tools.Editor.Contracts</AssemblyName>
  </PropertyGroup>

</Project>
