<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Lunar.Core</RootNamespace>
    <AssemblyName>Lunar.Core</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Authors>John Lamontagne</Authors>
    <Product>Lunar.Core</Product>
  </PropertyGroup>

</Project>
