<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Lunar.Core</RootNamespace>
    <AssemblyName>Lunar.Core</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Authors>John Lamontagne</Authors>
    <Product>Lunar.Core</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
    <PackageReference Include="AscensionGameDev.Lidgren.Network" Version="1.8.0.13" />
  </ItemGroup>

</Project>
