<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Lunar.Server</RootNamespace>
    <AssemblyName>Lunar.Server</AssemblyName>
    <Authors>John Lamontagne</Authors>
    <Product>Lunar.Server</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AscensionGameDev.Lidgren.Network" Version="1.8.0.13" />
    <PackageReference Include="IronPython" Version="3.4.2" />
    <PackageReference Include="IronPython.StdLib" Version="3.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lunar.Core\Lunar.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Server Data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
